Repository iver-wharf/rfcs, pull requests merged in 2021-09, with the labels that each got.

#17 AzureDevOps repos, and not projects
  _published/0017-azuredevops-repos-and-not-projects.md
Labels: rfc

#16 wharf-api endpoints cleanup
  _published/0016-wharf-api-endpoints-cleanup.md
Labels: rfc

#19 Fixed PR URL
  0000-template.md
  _published/0004-core-lib-repo.md
  _published/0008-codacy.md
  _published/0011-quay.io.md
  _published/0014-test-results-handling.md
  _published/0016-wharf-api-endpoints-cleanup.md
  _published/0017-azuredevops-repos-and-not-projects.md
Labels: documentation

#18 Added issue to RFC-0016
  _published/0016-wharf-api-endpoints-cleanup.md
Labels: documentation

#20 Added issue to RFC-0014
  _published/0014-test-results-handling.md
Labels: documentation

#13 Authentication and Authorisation
  _published/0013-authentication.md
  _published/0016-wharf-api-endpoints-cleanup.md
  _published/0017-azuredevops-repos-and-not-projects.md
  assets/auth-map-v2.PNG
Labels: rfc

#21 Change from issue to milestone
  _published/0016-wharf-api-endpoints-cleanup.md
Labels: documentation

#22 Added header styling
  _sass/custom/custom.scss
Labels: enhancement
